[project]
name = "preventmaker"
version = "0.1.0"
description = "Una semplice interfaccia grafica per poter creare preventivi velocemente e facilmente"
requires-python = ">=3.12"
dependencies = [
    "pyqt6",
    "reportlab",
    "pypdf2",
    "pyqt6-webengine",
    "mysql-connector-python",
    "pyinstaller",
    "qrcode>=8.2",
    "cryptography>=45.0.3",
    "opencv-python>=4.11.0.86",
    "pyzbar>=0.1.9",
    "notebook>=7.4.3",
    "python-dotenv>=1.1.0",
]
